---
kind: pipeline
type: docker
name: default

steps:
  - name: prepare
    image: plugins/docker
    commands:
      - docker build -f PrepareDockerfile -t jobrunr.io/build-container:1.0 .
    volumes:
      - name: dockersock
        path: /var/run/docker.sock

  - name: restore-node-modules-cache
    image: meltwater/drone-cache
    settings:
      backend: "filesystem"
      restore: true
      cache_key: "node_modules"
      archive_format: "gzip"
      mount:
        - 'core/src/main/resources/org/jobrunr/dashboard/frontend/node_modules'
    volumes:
      - name: node-modules-cache
        path: /tmp/cache

  - name: build-frontend
    image: node:12
    commands:
      - cd core/src/main/resources/org/jobrunr/dashboard/frontend
      - npm install
      - npm run build

  - name: save-node-modules-cache
    image: meltwater/drone-cache
    settings:
      backend: "filesystem"
      rebuild: true
      cache_key: "node_modules"
      archive_format: "gzip"
      mount:
        - 'core/src/main/resources/org/jobrunr/dashboard/frontend/node_modules'
    volumes:
      - name: node-modules-cache
        path: /tmp/cache

  - name: build
    image: jobrunr.io/build-container:1.0
    commands:
      - gradle --no-daemon clean build
      #- gradle assemble :tests:e2e-ui-gson:test :tests:e2e-ui-jackson:test  --tests org.jobrunr.tests.e2e.**
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: gradle-cache
        path: /home/gradle/.gradle
      - name: maven-local
        path: /root/.m2
      - name: reports
        path: /tmp/reports

  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: SLACK_WEBHOOK
      channel: drone
    when:
      status: [ success, failure ]

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: gradle-cache
    host:
      path: /tmp/jobrunr/cache/gradle
  - name: node-modules-cache
    host:
      path: /tmp/jobrunr/cache/node_modules
  - name: maven-local
    host:
      path: /tmp/jobrunr/cache/m2
  - name: reports
    host:
      path: /tmp/jobrunr/reports


---
kind: pipeline
type: docker
name: release

steps:
  - name: build
    image: jobrunr.io/build-container:1.0
    commands:
      - gradle --no-daemon clean build
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: gradle-cache
        path: /home/gradle/.gradle
      - name: maven-local
        path: /root/.m2
      - name: reports
        path: /tmp/reports

  - name: upload-to-github
    image: plugins/github-release
    settings:
      api_key:
        from_secret: GITHUB_TOKEN
      files: core/build/libs/*
    when:
      event: tag

  - name: upload-to-bintray
    image: jobrunr.io/build-container:1.0
    environment:
      BINTRAY_USER:
        from_secret: BINTRAY_USER
      BINTRAY_APIKEY:
        from_secret: BINTRAY_APIKEY
    commands:
      - gradle --no-daemon bintrayUpload
    volumes:
      - name: maven-local
        path: /root/.m2

  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: SLACK_WEBHOOK
      channel: drone
    when:
      status: [ success, failure ]

trigger:
  event:
    - tag

volumes:
  - name: maven-local
    host:
      path: /tmp/jobrunr/cache/m2
